[tool.black]
line-length = 120
target-version = ['py38']

[tool.isort]
line_length = 120
multi_line_output = 3
include_trailing_comma = true

[tool.flake8]
max-line-length = 120

[tool.mypy]
python_version = 3.8

[tool.pytest]
addopts = "--cov=src --cov-report=term-missing --cov-report=xml --cov-report=html --cov-fail-under=100"
pythonpath = ["src"]
python_files = "test_*.py"
python_classes = "Test*"


